# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/e3478028-021d-44f3-9791-b6f0449f1c0c";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/e3478028-021d-44f3-9791-b6f0449f1c0c";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7712-300E";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/b1ac6baf-41f6-4462-9e45-6e1c7486f0e3";
      fsType = "ext4";
    };

  #fileSystems."/var/lib/vm" =
  #  { device = "/dev/disk/by-uuid/521619f4-e81e-4ddd-9e32-075102497033";
  #    fsType = "btrfs";
  #    options = [ "subvol=root" ];
  #  };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/9eb82a75-7f79-4c3b-aa31-69c6aafab647"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
