[general]
modes=floating,click

[mode_floating]
source=detect
label_color=#fffd
label_select_color=#fd0d
unselectable_bg_color=#2226
selectable_bg_color=#1718
selectable_border_color=#040c
label_font_family=Cascadia Mono
label_font_size=12 50% 100
label_symbols=abcdefghijklmnopqrstuvwxyz

[mode_click]
button=left

